### ISSUE TITLE
broken conversion of lcio particle IDs that were not created using the PID handler

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/k4EDM4hep2LcioConv#62]
#51 breaks conversion of lcio particle IDs that were not created using the PID handler. I don't know if we consider this a bug but for instance `TrueJet` output seems to fail in 

https://github.com/key4hep/k4EDM4hep2LcioConv/blob/016c9ebf184f3b1ecd66ce4670007af1c3f90c82/k4EDM4hep2LcioConv/include/k4EDM4hep2LcioConv/k4Lcio2EDM4hepConv.ipp#L170-L182

and I suspect this is because it has no algorithm id as it does not use the PIDHandler but adds the PID directly like [here](https://github.com/iLCSoft/MarlinReco/blob/5c8162cf2362c5a5a5815032bb469f07ff506031/Analysis/TrueJet/src/TrueJet.cc#L527-L531)
```c++
        ParticleIDImpl* pid = new ParticleIDImpl; 
        pid->setPDG(k[elementon[i_jet]][2]);
        pid->setType(pid_type[i_jet]);
        true_jet->addParticleID(pid);
        true_jet->ext<TJindex>()=i_jet; 
```

I did not check if any other processors do the same, it might be quicker to just make TrueJet use the PIDHandler... :)

**Comment by tmadlener** [comment]
I would consider this a bug in `TrueJet`. 

> I did not check if any other processors do the same, it might be quicker to just make TrueJet use the PIDHandler... :)

I think so, yes.
